# -------------------------------
#              FOOT!?
# -------------------------------

# Colorscheme
include = ~/.config/foot/catppuccin-mocha

# Font & Size
font = JetBrainsMono Nerd Font : size=10

[main]
pad = 15x15
underline-offset = 4

[cursor]
style = beam

[scrollback]
lines = 10000
indicator-position = none

[key-bindings]
scrollback-up-line = Control+Shift+K
scrollback-down-line = Control+Shift+J
